# Generated by Django 4.1.5 on 2023-01-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_receiver_alter_message_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='createdAt',
            new_name='created_At',
        ),
    ]
